import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  ArrowLeft,
  ArrowRight,
  Eye,
  EyeOff,
  PlayCircle,
  Turtle,
  Volume2
} from "lucide-react";
import "./styles.css";

// Where audio clips live. Default: audio/ under the base path (works for both
// local dev with clips in public/audio/ and Pages deploy where CI extracts them).
// Override with VITE_AUDIO_BASE_URL for external hosting (CDN, bucket, etc.).
const AUDIO_BASE_URL = (import.meta.env.VITE_AUDIO_BASE_URL || "audio/").replace(/\/?$/, "/");
const RESOLVED_AUDIO_BASE = AUDIO_BASE_URL.startsWith("http") ? AUDIO_BASE_URL : `${import.meta.env.BASE_URL}${AUDIO_BASE_URL}`;

// Where the pre-built reader dataset lives (generated by build_reader_data.py).
// A base-prefixed URL is used so the site works both at "/" and at "/repo-name/".
const READER_JSON_URL = `${import.meta.env.BASE_URL}reader.json`;

const ROWS_PER_PAGE_DEFAULT = 24;

function formatClock(seconds) {
  if (!Number.isFinite(seconds) || seconds < 0) return "0:00";
  const total = Math.floor(seconds);
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function paginate(rows, rowsPerPage) {
  const pages = [];
  let current = [];
  for (const row of rows) {
    current.push(row);
    if (current.length >= rowsPerPage && row.kind === "sentence") {
      pages.push(current);
      current = [];
    }
  }
  if (current.length) pages.push(current);
  return pages.length ? pages : [[]];
}

function ReaderAudioPlayer({ selection }) {
  const audioRef = useRef(null);
  const rafRef = useRef(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [mode, setMode] = useState("normal");

  useEffect(() => {
    const player = audioRef.current;
    if (!player || !selection?.audio?.url) return;
    player.pause();
    player.currentTime = 0;
    player.playbackRate = 1;
    setMode("normal");
    setCurrentTime(0);
    player.play().catch(() => setIsPlaying(false));
  }, [selection]);

  useEffect(() => {
    if (!isPlaying) {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
      return;
    }
    const tick = () => {
      const player = audioRef.current;
      if (player) setCurrentTime(player.currentTime);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    };
  }, [isPlaying]);

  async function replay(rate, nextMode) {
    const player = audioRef.current;
    if (!player) return;
    player.pause();
    player.currentTime = 0;
    player.playbackRate = rate;
    setMode(nextMode);
    await player.play();
  }

  const audio = selection?.audio;
  const progress = duration ? (currentTime / duration) * 100 : 0;
  return (
    <div className="reader-player">
      <div>
        <span className="task-label">Selected audio</span>
        <strong>{selection?.text || "Select highlighted text"}</strong>
      </div>
      {audio?.url ? (
        <div className="reader-player-controls">
          <button type="button" className="audio-play-button" onClick={() => replay(1, "normal")}>
            <PlayCircle size={17} /> Normal
          </button>
          <button type="button" className="audio-play-button slow" onClick={() => replay(0.75, "slow")}>
            <Turtle size={17} /> Slow
          </button>
          <div className="audio-progress-column">
            <div className="audio-scrubber" role="progressbar" aria-valuemin={0} aria-valuemax={duration || 0} aria-valuenow={currentTime}>
              <div className="audio-scrubber-fill" style={{ width: `${progress}%` }} />
            </div>
            <div className="audio-progress-meta">
              <span className="audio-mode-label">{isPlaying ? `Playing ${mode}` : audio.label}</span>
              <span className="audio-time">{formatClock(currentTime)} / {formatClock(duration)}</span>
            </div>
          </div>
          <audio
            ref={audioRef}
            preload="metadata"
            src={audio.url}
            onPlay={() => setIsPlaying(true)}
            onPause={() => setIsPlaying(false)}
            onEnded={() => {
              setIsPlaying(false);
              setCurrentTime(0);
            }}
            onLoadedMetadata={(event) => setDuration(event.currentTarget.duration || 0)}
            onDurationChange={(event) => setDuration(event.currentTarget.duration || 0)}
          />
        </div>
      ) : (
        <span className="reader-empty-player">Tap a Hungarian line to play its recording.</span>
      )}
    </div>
  );
}

function FsiReader({ dataset }) {
  const rowsPerPage = dataset.rows_per_page || ROWS_PER_PAGE_DEFAULT;
  const pages = React.useMemo(
    () => paginate(dataset.rows || [], rowsPerPage),
    [dataset, rowsPerPage]
  );
  const totalPages = pages.length;

  const [page, setPage] = useState(1);
  const [draftPage, setDraftPage] = useState("1");
  const [selection, setSelection] = useState(null);
  const [activeId, setActiveId] = useState(null);
  const [hideEn, setHideEn] = useState(false);
  const [hideHu, setHideHu] = useState(false);
  const [revealed, setRevealed] = useState(() => new Set());
  const [autoPlayOnReveal, setAutoPlayOnReveal] = useState(() => {
    try {
      return localStorage.getItem("fsiAutoPlayOnReveal") !== "false";
    } catch {
      return true;
    }
  });

  useEffect(() => {
    setDraftPage(String(page));
  }, [page]);

  function go(nextPage) {
    const target = Math.max(1, Math.min(Number(nextPage) || 1, totalPages));
    setPage(target);
    setActiveId(null);
    setRevealed(new Set());
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function play(row) {
    if (!row.audio) return;
    setActiveId(row.id);
    setSelection({
      text: row.hungarian,
      audio: { url: RESOLVED_AUDIO_BASE + row.audio, label: "FSI clip" },
      nonce: Date.now()
    });
  }

  function reveal(key) {
    setRevealed((prev) => {
      const next = new Set(prev);
      next.add(key);
      return next;
    });
  }

  function revealHu(row) {
    reveal(`hu:${row.id}`);
    if (autoPlayOnReveal) play(row);
  }

  function toggleAutoPlay(next) {
    setAutoPlayOnReveal(next);
    try {
      localStorage.setItem("fsiAutoPlayOnReveal", next ? "true" : "false");
    } catch {
      /* private mode etc. — ignore */
    }
  }

  function toggleHideEn() {
    setHideEn((v) => !v);
    setRevealed(new Set());
  }

  function toggleHideHu() {
    setHideHu((v) => !v);
    setRevealed(new Set());
  }

  const rows = pages[page - 1] || [];
  const pageControls = (
    <div className="reader-page-controls">
      <button type="button" className="secondary" onClick={() => go(page - 1)} disabled={page <= 1}>
        <ArrowLeft size={18} /> Previous
      </button>
      <label>
        Page
        <input
          value={draftPage}
          onChange={(event) => setDraftPage(event.target.value)}
          onBlur={() => go(draftPage)}
          onKeyDown={(event) => {
            if (event.key === "Enter") go(draftPage);
          }}
        />
        <span>of {totalPages}</span>
      </label>
      <button type="button" className="primary" onClick={() => go(page + 1)} disabled={page >= totalPages}>
        Next <ArrowRight size={18} />
      </button>
    </div>
  );

  return (
    <main className="reader-layout">
      <section className="reader-toolbar">
        <div>
          <span className="task-label">FSI Hungarian Basic Course</span>
          <h1>{dataset.title || "Volume 1 Reader"}</h1>
          <p>Tap any Hungarian line to hear its recording · {dataset.total_items} items</p>
          <label className="fsi-autoplay-toggle">
            <input
              type="checkbox"
              checked={autoPlayOnReveal}
              onChange={(event) => toggleAutoPlay(event.target.checked)}
            />
            Auto-play audio when a hidden Hungarian line is revealed
          </label>
        </div>
        {pageControls}
      </section>
      <ReaderAudioPlayer selection={selection} />
      <section className="fsi-book" aria-label={`FSI page ${page}`}>
        <div className="fsi-columns-head">
          <button
            type="button"
            className={`fsi-col-toggle${hideEn ? " on" : ""}`}
            onClick={toggleHideEn}
            aria-pressed={hideEn}
            title={hideEn ? "Show the English column" : "Hide the English column (tap words to reveal)"}
          >
            {hideEn ? <EyeOff size={14} /> : <Eye size={14} />}
            <span>English{hideEn ? " · hidden" : ""}</span>
          </button>
          <button
            type="button"
            className={`fsi-col-toggle${hideHu ? " on" : ""}`}
            onClick={toggleHideHu}
            aria-pressed={hideHu}
            title={hideHu ? "Show the Hungarian column" : "Hide the Hungarian column (tap words to reveal)"}
          >
            {hideHu ? <EyeOff size={14} /> : <Eye size={14} />}
            <span>Hungarian{hideHu ? " · hidden" : " · tap to play"}</span>
          </button>
        </div>
        {rows.map((row) => {
          const enHidden = hideEn && !revealed.has(`en:${row.id}`);
          const huHidden = hideHu && !revealed.has(`hu:${row.id}`);
          return (
            <div
              key={row.id}
              className={`fsi-row ${row.kind}${activeId === row.id ? " active" : ""}`}
            >
              {enHidden ? (
                <button
                  type="button"
                  className="fsi-en fsi-hidden"
                  onClick={() => reveal(`en:${row.id}`)}
                  title="Reveal English"
                >
                  <span className="fsi-mask">Reveal</span>
                </button>
              ) : (
                <div className="fsi-en">{row.english}</div>
              )}
              {huHidden ? (
                <button
                  type="button"
                  className="fsi-hu fsi-hidden"
                  onClick={() => revealHu(row)}
                  title="Reveal Hungarian"
                >
                  <span className="fsi-mask">Reveal</span>
                </button>
              ) : (
                <button
                  type="button"
                  className="fsi-hu"
                  onClick={() => play(row)}
                  disabled={!row.audio}
                  title={row.audio ? "Play recording" : "No audio"}
                >
                  <span className="fsi-hu-text" lang="hu">{row.hungarian}</span>
                  <Volume2 size={15} className="fsi-hu-icon" />
                </button>
              )}
            </div>
          );
        })}
      </section>
      <section className="reader-pager-bottom">{pageControls}</section>
      {dataset.source && (
        <footer className="fsi-source">
          <p>
            Audio &amp; text from the{" "}
            <a href={dataset.source.anki_url} target="_blank" rel="noreferrer noopener">
              {dataset.source.anki_name || dataset.source.deck}
            </a>{" "}
            Anki deck, built on the{" "}
            <a href={dataset.source.course_url} target="_blank" rel="noreferrer noopener">
              {dataset.source.course_name}
            </a>.
          </p>
          {dataset.source.apkg && (
            <p className="fsi-source-file">Imported from <code>{dataset.source.apkg}</code></p>
          )}
        </footer>
      )}
    </main>
  );
}

function Shell({ children }) {
  return (
    <div className="app-shell">
      <header className="app-top">
        <div className="brand">
          <div className="brand-mark">HU</div>
          <div>
            <strong>Hungarian FSI Course Audiobook</strong>
            <span>Volume 1</span>
          </div>
        </div>
      </header>
      {children}
    </div>
  );
}

function App() {
  const [dataset, setDataset] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(READER_JSON_URL)
      .then((r) => {
        if (!r.ok) throw new Error(`Could not load reader.json (${r.status})`);
        return r.json();
      })
      .then(setDataset)
      .catch((err) => setError(err.message));
  }, []);

  if (error) {
    return (
      <Shell>
        <main className="reader-layout">
          <section className="reader-error">
            <h1>Reader data missing</h1>
            <p>{error}</p>
            <p>
              Run <code>python scripts/build_reader_data.py</code> (see README) to
              generate <code>reader.json</code> from your Anki deck.
            </p>
          </section>
        </main>
      </Shell>
    );
  }
  if (!dataset) {
    return (
      <Shell>
        <main className="reader-layout">
          <div className="loading">Loading FSI reader…</div>
        </main>
      </Shell>
    );
  }
  return (
    <Shell>
      <FsiReader dataset={dataset} />
    </Shell>
  );
}

createRoot(document.getElementById("root")).render(<App />);
